theme: jekyll-theme-hacker
title: [Battle not with monsters, lest ye become a monster, and if you gaze into the abyss, the abyss gazes also into you]
description: [ Blog about Linux (Security | Malware Analysis | Reverse Engineering) ]
